version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - GLOBAL_ARTIFACT_URL_BASE=https://artifact.eventdata.crossref.org
     - REDDIT_APP_NAME=$REDDIT_APP_NAME
     - REDDIT_PASSWORD=$REDDIT_PASSWORD
     - REDDIT_CLIENT=$REDDIT_CLIENT
     - REDDIT_SECRET=$REDDIT_SECRET

    command: "lein test :unit"

